/**
 * WesBids — the bidding-range study, readable.
 *
 * Renders research/bidding-report.md (generated by `npm run research:bidding`
 * and bundled at build time via ?raw) into a navigable page: sticky table of
 * contents, per-context collapsible cards, a context filter, and
 * click-to-copy on every dealer filter expression.
 */

import './styles.css';
import './bidding.css';
import { h } from './ui/dom';
import { siteNav } from './ui/nav';
import { parseReport, slugify, type Block, type Inline } from './report-md';
import reportMd from '../research/bidding-report.md?raw';

// ---- Inline rendering -------------------------------------------------------

/** Wrap ♥/♦ glyphs in red spans; returns text/element nodes. */
function suitColored(text: string): Array<Node | string> {
  const out: Array<Node | string> = [];
  let buf = '';
  for (const ch of text) {
    if (ch === '♥' || ch === '♦') {
      if (buf) {
        out.push(buf);
        buf = '';
      }
      out.push(h('span', { class: 'suit-red' }, [ch]));
    } else buf += ch;
  }
  if (buf) out.push(buf);
  return out;
}

function inlineNodes(inline: Inline[]): Array<Node | string> {
  const out: Array<Node | string> = [];
  for (const tok of inline) {
    if (tok.t === 'text') out.push(...suitColored(tok.s));
    else if (tok.t === 'bold') out.push(h('strong', {}, suitColored(tok.s)));
    else out.push(h('code', { class: 'rep-code-inline', title: 'Click to copy' }, [tok.s]));
  }
  return out;
}

const NUMERIC_CELL = /^[\d\s.,%()\/±×–—+*-]*\d[\d\s.,%()\/±×–—+*-]*$/;

function cellIsNumeric(inline: Inline[]): boolean {
  if (inline.some((t) => t.t === 'code')) return false;
  const text = inline.map((t) => t.s).join('');
  return NUMERIC_CELL.test(text.replace(/\*\*/g, '').trim());
}

// ---- Block rendering --------------------------------------------------------

function tableEl(header: Inline[][], rows: Inline[][][]): HTMLElement {
  const thead = h('thead', {}, [h('tr', {}, header.map((c) => h('th', {}, inlineNodes(c))))]);
  const tbody = h(
    'tbody',
    {},
    rows.map((row) =>
      h(
        'tr',
        {},
        row.map((c) => h('td', { class: cellIsNumeric(c) ? 'num' : false }, inlineNodes(c))),
      ),
    ),
  );
  return h('div', { class: 'rep-table-wrap' }, [h('table', { class: 'rep-table' }, [thead, tbody])]);
}

function blockEl(b: Block): HTMLElement {
  switch (b.t) {
    case 'p':
      return h('p', { class: 'rep-p' }, inlineNodes(b.inline));
    case 'ul':
      return h('ul', { class: 'rep-ul' }, b.items.map((item) => h('li', {}, inlineNodes(item))));
    case 'table':
      return tableEl(b.header, b.rows);
    case 'code':
      return h('pre', { class: 'rep-code' }, [b.text]);
    default:
      return h('p', {}, []); // headings handled by the section builder
  }
}

// ---- Page assembly ----------------------------------------------------------

interface SubSection {
  el: HTMLDetailsElement;
  tocLink: HTMLAnchorElement;
  searchText: string;
}
interface Section {
  el: HTMLElement;
  tocLink: HTMLAnchorElement;
  subs: SubSection[];
  hasOwnContent: boolean;
}

function buildPage(blocks: Block[]): void {
  const title = blocks.find((b) => b.t === 'h1');
  const tocList = h('div', {}, []);
  const main = h('div', { class: 'bids-main' }, []);
  const sections: Section[] = [];
  const usedIds = new Set<string>();
  const uniqueId = (text: string): string => {
    let id = slugify(text) || 'section';
    let k = 2;
    while (usedIds.has(id)) id = `${slugify(text)}-${k++}`;
    usedIds.add(id);
    return id;
  };

  let section: Section | null = null;
  let sub: SubSection | null = null;

  const appendBlock = (b: Block): void => {
    const el = blockEl(b);
    if (sub) sub.el.append(el);
    else if (section) {
      section.el.append(el);
      section.hasOwnContent = true;
    } else main.append(el);
    if (sub) sub.searchText += ' ' + textOf(b);
  };

  for (const b of blocks) {
    if (b.t === 'h1') continue; // page header handles the title
    if (b.t === 'h2') {
      const id = uniqueId(b.text);
      const tocLink = h('a', { href: `#${id}` }, suitColored(b.text)) as HTMLAnchorElement;
      tocList.append(tocLink);
      const el = h('section', { class: 'rep-section', id }, [h('h2', {}, suitColored(b.text))]);
      main.append(el);
      section = { el, tocLink, subs: [], hasOwnContent: false };
      sections.push(section);
      sub = null;
      continue;
    }
    if (b.t === 'h3') {
      const id = uniqueId(b.text);
      const details = h('details', { class: 'rep-sub', id, open: true }, [
        h('summary', {}, suitColored(b.text)),
      ]) as HTMLDetailsElement;
      const tocLink = h('a', { href: `#${id}`, class: 'toc-h3' }, suitColored(b.text)) as HTMLAnchorElement;
      tocList.append(tocLink);
      (section?.el ?? main).append(details);
      sub = { el: details, tocLink, searchText: b.text.toLowerCase() };
      section?.subs.push(sub);
      continue;
    }
    appendBlock(b);
  }

  // ---- controls
  const filterInput = h('input', {
    class: 'bids-filter',
    type: 'search',
    placeholder: 'Filter contexts… e.g. "1S (2H)", "balance", "X"',
  }) as HTMLInputElement;
  const countEl = h('span', { class: 'bids-count' }, []);
  const expandBtn = h('button', { type: 'button' }, ['Expand all']);
  const collapseBtn = h('button', { type: 'button' }, ['Collapse all']);
  const setAllOpen = (open: boolean): void => {
    for (const s of sections) for (const d of s.subs) d.el.open = open;
  };
  expandBtn.addEventListener('click', () => setAllOpen(true));
  collapseBtn.addEventListener('click', () => setAllOpen(false));

  const applyFilter = (): void => {
    const q = filterInput.value.trim().toLowerCase();
    let shown = 0;
    let total = 0;
    for (const s of sections) {
      let anySub = false;
      for (const d of s.subs) {
        total++;
        const match = q === '' || d.searchText.includes(q);
        d.el.classList.toggle('hidden', !match);
        d.tocLink.classList.toggle('hidden', !match);
        if (match) {
          shown++;
          anySub = true;
          if (q !== '') d.el.open = true;
        }
      }
      const keepSection = q === '' || anySub || s.hasOwnContent;
      s.el.classList.toggle('hidden', !keepSection);
      s.tocLink.classList.toggle('hidden', !keepSection);
    }
    countEl.textContent = q === '' ? `${total} contexts` : `${shown} of ${total} contexts`;
  };
  filterInput.addEventListener('input', applyFilter);

  // ---- copy-to-clipboard on filter expressions
  const toast = h('div', { class: 'bids-toast' }, []);
  let toastTimer = 0;
  main.addEventListener('click', (ev) => {
    const target = (ev.target as HTMLElement).closest('code.rep-code-inline');
    if (!target) return;
    const expr = target.textContent ?? '';
    void navigator.clipboard?.writeText(expr).then(() => {
      toast.textContent = `Copied: ${expr}`;
      toast.classList.add('show');
      window.clearTimeout(toastTimer);
      toastTimer = window.setTimeout(() => toast.classList.remove('show'), 1600);
    });
  });

  // ---- assemble
  const app = document.getElementById('app')!;
  app.classList.add('bids-app');
  const toc = h('aside', { class: 'bids-toc' }, [
    h('p', { class: 'bids-toc-title' }, ['Contents']),
    tocList,
  ]);
  app.append(
    siteNav('bidding'),
    h('header', { class: 'app-header' }, [
      h('h1', {}, ['WesBids']),
      h('p', { class: 'tagline' }, [
        title && title.t === 'h1' ? title.text : 'Bidding ranges from championship data',
      ]),
    ]),
    h('div', { class: 'bids-controls' }, [filterInput, expandBtn, collapseBtn, countEl]),
    h('div', { class: 'bids-layout' }, [toc, main]),
    toast,
  );
  applyFilter();
}

/** Plain text of a block, for the context search index. */
function textOf(b: Block): string {
  switch (b.t) {
    case 'p':
      return b.inline.map((t) => t.s).join('').toLowerCase();
    case 'ul':
      return b.items.map((i) => i.map((t) => t.s).join('')).join(' ').toLowerCase();
    case 'table':
      return b.rows.map((r) => r.map((c) => c.map((t) => t.s).join('')).join(' ')).join(' ').toLowerCase();
    case 'code':
      return b.text.toLowerCase();
    default:
      return b.text.toLowerCase();
  }
}

buildPage(parseReport(reportMd));
